### ISSUE TITLE
Relationship are ignored when targets are not included

### ISSUE THREAD

**Issue by markpatton** [MarkoMilos/jsonapi#10]
Suppose I have a model with a relationship, an instance of that model, and a JSON API representation of that instance without any included resources. The instance has a relationship with a target object. The JSON API representation specifies the type and id of the target resource of the relationship. All of this works, I can correctly create the JSON API document and persist it.

But then when I retrieve the JSON API representation, the instance created has the relationship set to null. This seems odd to me. There is enough information to do better. The relationship target is not included, but since the type and id are present, the relationship target should be created with the id. Then the full target resource can be retrieved later if needed. Also the relationship object really needs to be represented in Document. Since it isn't, fixing this requires a lot of extra work.

**Comment by vadym-sedna** [comment]
In addition, `@ToOne` and `@ToMany` seem to be completely ignored for me.
I have to set programatically using
```
@RelationshipsObject
val relationships: Relationships?,
```

**Comment by MarkoMilos** [comment]
Can you provide an example of the classes that you want to serialize/deserialize to/from JSON and JSON itself. Without it, it is hard to tell what went wrong (if anything).

It seems to me that something is not used correctly and there are examples of what you want to achieve in the test. E.g. take a look at the `ResourceTypeAdapterTest` within this repository.

**Comment by markpatton** [comment]
@MarkoMilos This is true for everything as far as I can tell. See for example https://github.com/eclipse-pass/pass-support/blob/main/pass-data-client/src/main/java/org/eclipse/pass/support/client/model/Submission.java for how I am using the library. You can see that Submission has a relationship to a User object.

So persisting the objects works fine, but when I retrieve them without including a relationship in the response, relationships are null. To work around this I parse the json api response manually. See https://github.com/eclipse-pass/pass-support/blob/5365c1b322c43598338a8d1d9a0e0199206017e8/pass-data-client/src/main/java/org/eclipse/pass/support/client/JsonApiPassClient.java#L307C59-L307C59 

I did notice the relationships object, but I didn't try it because the documentation seemed to say it wouldn't play nicely with the To* annotations.

**Comment by MarkoMilos** [comment]
So if I understood you correctly - you are trying to deserialize JSON that has a `relationships` map but does not have any `included` resources within json, and you expect the library to create empty relationship instances with `type` and `id` assigned from that map? E.g. json like this:

```json
{
  "data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      }
    }
  }
}
```

If that is the case this library won't create instances of relationship fields by itself. It will only assign them if they are present within `data` or `included`.

You can use the `@RelationshipsObject` to get the `Relationships` that hold the whole map of relationships and you can use those to fetch more data for specific relationships when needed. E.g. in kotlin:

```
@Resource("articles")
class Article(
  // Standard resource object members
  @Type val type: String?,
  @Id val id: String?,
  @RelationshipsObject val relationships: Relationships?,

  
  // Attributes
  var title: String?,
  // ... 
  
  // Relationships
  @ToOne("author") val author: Person?,
  @ToMany("comments") val comments: List<Comment>?
  // ...
)
```

**Comment by markpatton** [comment]
@MarkoMilos Exactly. Ok. So it looks like instead of manully parsing the JSON API document, I could use a RelationshipsObject field to get the ids set the relationship targets.

And just as an aside, the other case where I need to manually hack the JSON API document is when doing a JSON API patch and I want to set a ToOne relationship to null. The default serialization will not included null relationship targets so I have to do it manually. See https://github.com/eclipse-pass/pass-support/blob/5365c1b322c43598338a8d1d9a0e0199206017e8/pass-data-client/src/main/java/org/eclipse/pass/support/client/JsonApiPassClient.java#L241.

**Comment by MarkoMilos** [comment]
Yes, since custom objects like `Submission`, `User` etc. can have more complex initialization (installation) the library does not know how to create an instance of them, and thus decision is not to create them at all. They will only be assigned via reflection if, and only if, they are present in `data` and/or `included` within the JSON document. 

So to parse JSON like this one
```json
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON:API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  }]
}
```

You would write something like
```kotlin
@Resource("articles")
class Article(

  // The "relationships" map will be parsed to this field
  @RelationshipsObject val relationships: Relationships?,

  // other fields
)
```

and then access the relationships like this:
```kotlin
article. relationships.get("comments")
```


When doing a patch request you want for serializer to create `relationships` map for you but you do not want to serialized `included` field in the document. 

Here you can use
```kotlin

// Example relationship fields initialization
val author = Autor(...)
val comments = listOf(comment1, comment2...)

// Target resource that we want to PATCH
val article = Article("Foo title", author, comments)

// Create a document that will be sent via PATCH request
Document.with(article)
  .includedSerialization(NONE) // Don't serialize included
  .build()
```

This will create JSON representation of the target resource such that it has proper `relationships` within the json but included won't be added to the document. E.g. output
```json
{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "Foo title"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      },
      "comments": {
        "data": [
          { "type": "comments", "id": "1" },
          { "type": "comments", "id": "2" }
        ]
      }
    }
  }
}
```

Which is exactly what you want per specification.

**Comment by markpatton** [comment]
It looks like the relationships object can solve the first issue.

For a patch with a ToOne relationships, object inclusion is not the issue I had. That actually seems to work ok. What is needed is that the serialization have a null value for the relationship when the relationship does not exist. If the null is not added to the serialization, then the relationship cannot be deleted.   

In any case, the original issue is solved. Thanks for the help!
