### ISSUE TITLE
can't parse back from JSON

### ISSUE THREAD

**Issue by NunoCardoso** [MarkoMilos/jsonapi#13]
Hi, 

I am having trouble parsing back the JSON:API I write with jsonapi. 

This is the JSON.

{"meta":{"created":"2023-07-31T13:09:13Z"},"links":{"self":"/path/85699a3b-fe81-41bc-aae0-9ea4aa0b15ca"},"data":{"type":"job","relationships":{"files":{"data":[{"type":"file","id":"export.csv"}]}},"attributes":{"status":"Completed","jobId":"85699a3b-fe81-41bc-aae0-9ea4aa0b15ca"}},"included":[{"type":"file","id":"export.csv","attributes":{"filename":"export.csv","location":"oci://path/export.csv"}}]}

all code is basically a copy/paste from the README examples. I am getting this error, in one project: 

com.squareup.moshi.JsonDataException: Required value 'id' missing at $.included[0].attributes

and I also get a similar error in another, with a different JSON:

Required value 'id' missing at $.data[0].attributes

any idea why it is happening?

**Comment by vadym-sedna** [comment]
+1
can't deserialize valid JsonAPI string into a Document if `included` exists in JSON.
If `included` is removed, then data.relationships are not deserialized :/

**Comment by vadym-ua** [comment]
looks like all the fields on the resource object must be nullable.
For example, I use Kotlin, so every field on a @Resource annotated class (including relationship resources) must be explicitly nullable `? = null`
```
@Resource("file")
data class FileResource(
    @Id
    val id: String? = null,
    val filename: String? = null,
    val location: String? = null
)
```

**Comment by MarkoMilos** [comment]
Yes, fields have to be nullable due to the nature of deserializing JSON to objects. When the object is created some value has to be assigned to the field, if the value is not present in JSON (there is no guarantee for it) then the field will be null.

There are other assert statements that will check if the deserialized resource object is valid according to JSON:API specification - for example from the specification:

> A “resource identifier object” MUST contain a type member. It MUST also contain an id member, except when it represents a new resource to be created on the server. In this case, a lid member MUST be included that identifies the new resource.

And for `ResourceIdentifier` in the library there is
```koltin
  init {
    require(type.isNotBlank()) {
      "A resource identifier MUST contain a type member but was blank."
    }
    require(!id.isNullOrBlank() || !lid.isNullOrBlank()) {
      "A resource identifier MUST contain an 'id' or 'lid' member but both were null or blank."
    }
  }
```

There are other checks ensuring that deserialized type is matching what is annotated on the deserialized object, etc.

**Comment by vadym-ua** [comment]
@MarkoMilos 
`There are other checks ensuring that deserialized type is matching what is annotated on the deserialized object, etc.` 
in my case, it checks only if `type` is present but isn't really checking if its a match with annotation.

Request payload:
```
{
    "data": {
        "type": "asfafasg",
        "lid": "0",
        "attributes": {
            "name": "Rocket"
        }
    }
}
```

Resource:
```
@Resource("myResource")
data class MyResource(
    @Id
    val id: String? = null,
    val name: String? = null,
)
```
Mvn Dependency:
```
<dependency>
                <groupId>com.markomilos.jsonapi</groupId>
                <artifactId>jsonapi-adapters</artifactId>
                <version>1.1.0</version>
            </dependency>
```
The rest, including `relationships` and `including` maps perfectly.

**Comment by MarkoMilos** [comment]
@vadym-sedna Ohh, sorry, forgot to mention that you need to opt in for strict type checking.

Like this:
```kotlin
    val factory = JsonApiFactory.Builder()
      .strictTypes(true)   // ENABLE HERE
      .addType(Article::class.java)
      .addType(Comment::class.java)
      .build()
```

This is documented in JsonApiFactory.Builder (see below c/p from source):
```kotlin
    /**
     * Enables strict type checking meaning that each serialization/deserialization of resource will assert if
     * `type` member matches with value provided with [Resource] for the target class. On mismatch exception is thrown.
     *
     * E.g. given that class Article that is annotated with `@Resource("articles")` is being deserialized, when provided
     * json for deserialization is "{"type":"dinosaur"....}", then exception will be thrown stating that "articles"
     * was expected but "dinosaur" was found.
     *
     * By default strict type checking is disabled.
     */
    fun strictTypes(enabled: Boolean) = apply {
      strictTypes = enabled
    }
```
