### ISSUE TITLE
I think this need to be fixed

### ISSUE THREAD

**Issue by Baniares** [MarkoMilos/jsonapi#2]
According to the 1.1 specification `LID` **MAY** be present but is not really required for client side created resources

https://github.com/MarkoMilos/jsonapi/blob/711533f1e011f70e2ab8511cf7fb914b0dd29235/jsonapi-adapters/src/main/java/jsonapi/ResourceIdentifier.kt#L33

reference:
https://jsonapi.org/format/1.1/#document-resource-objects

**Comment by MarkoMilos** [comment]
True, the next version will include a fix for this.

**Comment by markoilicic** [comment]
@MarkoMilos I have opened PR with the fix for the issue: https://github.com/MarkoMilos/jsonapi/pull/3

**Comment by MarkoMilos** [comment]
Fixed in latest release :)
