### ISSUE TITLE
Incremental annotation processor

### ISSUE THREAD

**Issue by scruffyfox** [MarkoMilos/jsonapi#8]
Are there any plans to implement incremental processing for the annotation library? 

```
The following annotation processors are not incremental: jsonapi-compiler-1.0.0.jar (com.markomilos.jsonapi:jsonapi-compiler:1.0.0).
Make sure all annotation processors are incremental to improve your build speed.
```

**Comment by MarkoMilos** [comment]
Will try to look into this by the end of the week :) 

In the meantime, if you are able to send PR, I would appreciate it 🙇‍♂️

**Comment by scruffyfox** [comment]
@MarkoMilos if I could I would! I know very little about annotation processing libraries unfortunately

**Comment by MarkoMilos** [comment]
Support for incremental annotation processing is added in the latest release 1.1.0.

**Comment by scruffyfox** [comment]
Awesome thank you!
